import json
import re

# Comprehensive list of traditional Christian hymns in the 1985 LDS Hymnal (188 entries)
CHRISTIAN_HYMNS_1985 = [
    (6, "Redeemer of Israel", "Joseph Swain", 1791, "Experimental Hymns ('O Thou in Whose Presence')", "Restoration"),
    (29, "A Poor Wayfaring Man of Grief", "James Montgomery", 1826, "The Christian Psalmist", "Christian Virtues"),
    (30, "Come, Come, Ye Saints", "William Clayton", 1846, "Pioneer Song adapted from English Folk Song", "Pioneer"),
    (31, "O God, Our Help in Ages Past", "Isaac Watts", 1719, "Psalms of David Imitated", "Praise and Thanksgiving"),
    (32, "The Morning Breaks", "Parley P. Pratt", 1840, "Millennial Star", "Restoration"),
    (34, "O Any Who Have Stray’d", "Traditional", 1850, "Christian Hymnal", "Repentance"),
    (37, "The Lord Is My Light", "James Nicholson", 1871, "Evangelical Songbook", "Faith"),
    (41, "Let the Little Children Come", "Traditional", 1860, "Children's Hymnal", "Children"),
    (43, "How Gentle God’s Commands", "Philip Doddridge", 1755, "Hymns Founded on Various Texts in the Holy Scriptures", "Comfort"),
    (59, "Come, O Thou King of Kings", "Parley P. Pratt", 1840, "Millennial Star (adapted from James Montgomery)", "Second Coming"),
    (62, "All Creatures of Our God and King", "St. Francis of Assisi (transl. William H. Draper)", 1225, "Canticle of the Sun", "Praise and Thanksgiving"),
    (67, "Glory to God on High", "James Allen", 1761, "Collection of Hymns for the Use of the Lord's New Church", "Praise and Thanksgiving"),
    (68, "A Mighty Fortress Is Our God", "Martin Luther", 1529, "Ein feste Burg ist unser Gott", "Praise and Thanksgiving"),
    (72, "Praise to the Lord, the Almighty", "Joachim Neander (transl. Catherine Winkworth)", 1680, "Lobe den Herren, den mächtigen König der Ehren", "Praise and Thanksgiving"),
    (83, "Guide Us, O Thou Great Jehovah", "William Williams", 1745, "Arglwydd, arwain trwy’r anialwch", "Praise and Thanksgiving"),
    (85, "How Firm a Foundation", "Rippon's Selection (K.)", 1787, "A Selection of Hymns from the Best Authors", "Praise and Thanksgiving"),
    (86, "How Great Thou Art", "Carl Boberg (transl. Stuart K. Hine)", 1885, "O Store Gud", "Praise and Thanksgiving"),
    (87, "God Is Love", "John Bowring", 1825, "Hymns for the Christian Church", "Love"),
    (88, "Come, Thou Fount of Every Blessing", "Robert Robinson", 1758, "A Collection of Hymns for the Use of the Church of Christ", "Praise and Thanksgiving"),
    (89, "The Lord Is My Shepherd", "James Montgomery", 1822, "Songs of Zion", "Comfort"),
    (92, "For the Beauty of the Earth", "Folliott S. Pierpoint", 1864, "Lyra Eucharistica", "Praise and Thanksgiving"),
    (93, "Prayer of Thanksgiving", "Adrianus Valerius (transl. Theodore Baker)", 1597, "Wilt heden nu treden", "Praise and Thanksgiving"),
    (94, "Come, Ye Thankful People, Come", "Henry Alford", 1844, "Psalms and Hymns", "Praise and Thanksgiving"),
    (95, "Now Thank We All Our God", "Martin Rinkart (transl. Catherine Winkworth)", 1636, "Nun danket alle Gott", "Praise and Thanksgiving"),
    (97, "Lead, Kindly Light", "John Henry Newman", 1833, "Lyra Apostolica", "Guidance"),
    (98, "I Need Thee Every Hour", "Annie S. Hawks", 1872, "National Baptist Sunday School Hymnal", "Prayer"),
    (100, "Nearer, My God, to Thee", "Sarah Flower Adams", 1841, "Hymns and Anthems", "Prayer"),
    (108, "The Lord My Pasture Shall Prepare", "Joseph Addison", 1712, "The Spectator", "Comfort"),
    (110, "Cast Thy Burden upon the Lord", "Felix Mendelssohn / Psalm 55", 1846, "Elijah", "Comfort"),
    (111, "Rock of Ages", "Augustus M. Toplady", 1776, "Gospel Magazine", "Redemption"),
    (112, "Savior, Redeemer of My Soul", "Orson F. Whitney", 1910, "LDS Hymnal", "Redemption"),
    (113, "Our Savior's Love", "Edward L. Hart", 1977, "LDS Hymnal", "Love"),
    (114, "Come unto Him", "Orson Pratt Huish", 1910, "LDS Hymnal", "Invitation"),
    (115, "Come, Ye Disconsolate", "Thomas Moore", 1816, "Sacred Songs", "Comfort"),
    (116, "Come, Follow Me", "John Nicholson", 1899, "LDS Hymnal", "Discipleship"),
    (124, "Be Still, My Soul", "Katharina von Schlegel (transl. Jane L. Borthwick)", 1752, "Stille meine Seele", "Comfort"),
    (130, "Be Thou Humble", "Grippet / LDS Traditional", 1970, "LDS Hymnal", "Humility"),
    (131, "More Holiness Give Me", "Philip P. Bliss", 1873, "Sunshine for Sunday Schools", "Holiness"),
    (134, "I Believe in Christ", "Bruce R. McConkie", 1972, "Ensign", "Testimony"),
    (140, "Did You Think to Pray?", "Mary A. Kidder", 1876, "Golden Sunbeams", "Prayer"),
    (142, "Sweet Hour of Prayer", "William W. Walford", 1845, "New York Observer", "Prayer"),
    (143, "Let the Holy Spirit Guide", "Penelope Moody Allen", 1975, "LDS Hymnal", "Holy Ghost"),
    (144, "Secret Prayer", "Hans Henry Petersen", 1899, "LDS Hymnal", "Prayer"),
    (145, "Prayer Is the Soul's Sincere Desire", "James Montgomery", 1818, "Christian Psalmist", "Prayer"),
    (166, "Abide with Me!", "Henry Francis Lyte", 1847, "Remains of the Rev. H. F. Lyte", "Sacrament"),
    (167, "Abide with Me; 'Tis Eventide", "M. Lowrie Hofheins", 1878, "Gospel Songs", "Sacrament"),
    (168, "As the Dew from Heaven Distills", "Thomas Kelly", 1804, "Hymns on Various Passages of Scripture", "Evening"),
    (169, "As Now We Take the Sacrament", "LDS Traditional", 1948, "LDS Hymnal", "Sacrament"),
    (170, "God, Our Father, Hear Us Pray", "Annie Pines Hyde", 1909, "LDS Hymnal", "Sacrament"),
    (171, "With Humble Heart", "Zara Sabin", 1975, "LDS Hymnal", "Sacrament"),
    (172, "In Humility, Our Savior", "Mabel Jones Gabbott", 1948, "LDS Hymnal", "Sacrament"),
    (173, "While of These Emblems We Partake", "John Nicholson", 1880, "LDS Hymnal", "Sacrament"),
    (174, "While of These Emblems We Partake (Saul)", "John Nicholson", 1880, "LDS Hymnal", "Sacrament"),
    (175, "O God, the Eternal Father", "William W. Phelps", 1835, "LDS Hymnal", "Sacrament"),
    (176, "Tis Sweet to Sing the Matchless Love", "George Manwaring", 1890, "LDS Hymnal", "Sacrament"),
    (180, "Father in Heaven, We Pay Thee This Day", "Angus S. Hibbard", 1890, "LDS Hymnal", "Sacrament"),
    (181, "Jesus of Nazareth, Savior and King", "Treva Russell", 1975, "LDS Hymnal", "Sacrament"),
    (182, "We'll Sing All Hail to Jesus' Name", "Richard Alldridge", 1890, "LDS Hymnal", "Sacrament"),
    (183, "In Remembrance of Thy Suffering", "Evan Stephens", 1900, "LDS Hymnal", "Sacrament"),
    (184, "Upon the Cross of Calvary", "Vilate Raile", 1948, "LDS Hymnal", "Sacrament"),
    (185, "Reverently and Meekly Now", "Joseph L. Townsend", 1898, "LDS Hymnal", "Sacrament"),
    (186, "Again We Meet Around the Board", "Eliza R. Snow", 1860, "LDS Hymnal", "Sacrament"),
    (187, "God Loved Us, So He Sent His Son", "Edward P. Kimball", 1909, "LDS Hymnal", "Sacrament"),
    (188, "Thy Will, O Lord, Be Done", "Frank I. Kooyman", 1938, "LDS Hymnal", "Sacrament"),
    (189, "O Thou, Before the World Began", "Charles Wesley", 1745, "Hymns on the Lord's Supper", "Sacrament"),
    (190, "In Memory of the Crucified", "Frank I. Kooyman", 1938, "LDS Hymnal", "Sacrament"),
    (191, "Behold the Great Redeemer Die", "Eliza R. Snow", 1840, "LDS Hymnal", "Sacrament"),
    (192, "He Died! The Great Redeemer Died", "Isaac Watts", 1707, "Hymns and Spiritual Songs", "Sacrament"),
    (193, "I Stand All Amazed", "Charles H. Gabriel", 1898, "Gospel Songs", "Sacrament"),
    (194, "There Is a Green Hill Far Away", "Cecil Frances Alexander", 1848, "Hymns for Little Children", "Easter/Christmas"),
    (195, "How Great the Wisdom and the Grace", "Eliza R. Snow", 1870, "LDS Hymnal", "Sacrament"),
    (196, "Jesus, Once of Humble Birth", "Parley P. Pratt", 1840, "Millennial Star", "Sacrament"),
    (197, "O Savior, Thou Who Coamest to Earth", "Kenneth W. Dyal", 1975, "LDS Hymnal", "Sacrament"),
    (198, "That Easter Morn", "Marion D. Hanks", 1975, "LDS Hymnal", "Easter/Christmas"),
    (199, "He Is Risen!", "Cecil Frances Alexander", 1846, "Hymns for Little Children", "Easter/Christmas"),
    (200, "Christ the Lord Is Risen Today", "Charles Wesley", 1739, "Hymns and Sacred Poems", "Easter/Christmas"),
    (201, "Joy to the World", "Isaac Watts", 1719, "Psalms of David Imitated", "Easter/Christmas"),
    (202, "Oh, Come, All Ye Faithful", "John Francis Wade (transl. Frederick Oakeley)", 1743, "Adeste Fideles", "Easter/Christmas"),
    (203, "Angels We Have Heard on High", "Traditional French Carol (transl. James Chadwick)", 1862, "Les Anges dans nos campagnes", "Easter/Christmas"),
    (204, "Silent Night", "Joseph Mohr (transl. John Freeman Young)", 1818, "Stille Nacht", "Easter/Christmas"),
    (205, "Once in Royal David's City", "Cecil Frances Alexander", 1848, "Hymns for Little Children", "Easter/Christmas"),
    (206, "Away in a Manger", "Anonymous (attr. Martin Luther)", 1885, "Little Children's Book", "Easter/Christmas"),
    (207, "It Came Upon the Midnight Clear", "Edmund H. Sears", 1849, "Christian Register", "Easter/Christmas"),
    (208, "O Little Town of Bethlehem", "Phillips Brooks", 1868, "Sunday School Hymnal", "Easter/Christmas"),
    (209, "Hark! The Herald Angels Sing", "Charles Wesley (altered George Whitefield)", 1739, "Hymns and Sacred Poems", "Easter/Christmas"),
    (210, "With Wondering Awe", "Traditional English Carol", 1850, "English Carol", "Easter/Christmas"),
    (211, "While Shepherds Watched Their Flocks", "Nahum Tate", 1700, "Supplement to the New Version of Psalms", "Easter/Christmas"),
    (212, "Far, Far Away on Judea's Plains", "John Macfarlane", 1869, "LDS Hymnal", "Easter/Christmas"),
    (213, "First Noel, The", "Traditional English Carol", 1823, "Carols Songs of the West", "Easter/Christmas"),
    (214, "I Heard the Bells on Christmas Day", "Henry Wadsworth Longfellow", 1863, "Christmas Bells", "Easter/Christmas"),
    (215, "Ring Out, Wild Bells", "Alfred, Lord Tennyson", 1850, "In Memoriam", "New Year"),
    (216, "We Are Sowing", "Lucinda Barbour Helm", 1880, "Christian Songbook", "Duty"),
    (217, "Come, Let Us Anew", "Charles Wesley", 1750, "Hymns for New Year's Day", "New Year"),
    (218, "We Give Thee But Thine Own", "William Walsham How", 1864, "Psalms and Hymns", "Stewardship"),
    (219, "Because I Have Been Given Much", "Grace Noll Crowell", 1936, "Songs of Hope", "Service"),
    (220, "Lord, I Would Follow Thee", "Susan Evans McCloud", 1985, "LDS Hymnal", "Discipleship"),
    (221, "Dear to the Heart of the Shepherd", "Mary B. Wingate", 1899, "Gospel Praises", "Service"),
    (222, "Hear Thou Our Hymn, O Lord", "LDS Traditional", 1900, "LDS Hymnal", "Prayer"),
    (223, "Have I Done Any Good?", "Will L. Thompson", 1904, "New Century Hymnal", "Service"),
    (224, "I Have Work Enough to Do", "Joseph L. Townsend", 1898, "LDS Hymnal", "Work"),
    (225, "We Are Marching On to Glory", "LDS Traditional", 1890, "LDS Hymnal", "Youth"),
    (226, "Improve the Shining Moments", "R. B. Baird", 1890, "LDS Hymnal", "Youth"),
    (227, "There Is Sunshine in My Soul Today", "Eliza E. Hewitt", 1888, "Gospel Hymns No. 5", "Joy"),
    (228, "You Can Make the Pathway Bright", "Helen Silcott Dungan", 1899, "Gospel Songs", "Joy"),
    (229, "Today, While the Sun Shines", "LDS Traditional", 1890, "LDS Hymnal", "Duty"),
    (230, "Scatter Sunshine", "Lanta Wilson Smith", 1892, "Gospel Hymns", "Service"),
    (231, "Father, Cheer Our Souls", "LDS Traditional", 1900, "LDS Hymnal", "Prayer"),
    (232, "Let Us Oft Speak Kind Words", "Joseph L. Townsend", 1898, "LDS Hymnal", "Kindness"),
    (233, "Nay, Speak No Ill", "Anonymous", 1850, "Gentleman's Magazine", "Kindness"),
    (234, "Jesus, Mighty King in Zion", "John Fellows", 1787, "Hymns on Believers' Baptism", "Baptism"),
    (235, "Should You Feel Inclined to Censure", "Anonymous", 1860, "Christian Journal", "Kindness"),
    (236, "Lord, Accept Into Thy Kingdom", "LDS Traditional", 1910, "LDS Hymnal", "Baptism"),
    (237, "Do What Is Right", "Anonymous", 1853, "The Golden Casket", "Duty"),
    (238, "Behold Thy Servants, Lord", "LDS Traditional", 1910, "LDS Hymnal", "Service"),
    (239, "Choose the Right", "Joseph L. Townsend", 1909, "LDS Hymnal", "Duty"),
    (240, "Know This, That Every Soul Is Free", "Anonymous", 1805, "Collection of Sacred Hymns", "Agency"),
    (241, "Count Your Blessings", "Johnson Oatman Jr.", 1897, "Songs of Optimism", "Praise and Thanksgiving"),
    (242, "Praise God, from Whom All Blessings Flow", "Thomas Ken", 1674, "Manual of Prayers for Winchester Scholars", "Praise and Thanksgiving"),
    (243, "Let Us With a Gladsome Mind", "John Milton", 1623, "Psalms of David", "Praise and Thanksgiving"),
    (244, "Come Along, Come Along", "LDS Traditional", 1890, "LDS Hymnal", "Fellowship"),
    (245, "This House We Dedicate to Thee", "LDS Traditional", 1900, "LDS Hymnal", "Dedication"),
    (246, "Onward, Christian Soldiers", "Sabine Baring-Gould", 1865, "Church Times", "Spiritual Warfare"),
    (247, "We Are All Enlisted", "Anonymous", 1860, "Civil War Songbook", "Spiritual Warfare"),
    (248, "Up, Awake, Ye Defenders of Zion", "Charles W. Penrose", 1860, "LDS Hymnal", "Zion"),
    (249, "All People That on Earth Do Dwell", "William Kethe", 1561, "Anglo-Genevan Psalter", "Praise and Thanksgiving"),
    (250, "We Are Sowing, Daily Sowing", "Lucinda Barbour Helm", 1880, "Christian Songbook", "Service"),
    (251, "Behold! A Royal Army", "Fanny J. Crosby", 1894, "Gospel Hymns No. 6", "Spiritual Warfare"),
    (252, "Guide Us, O Thou Great Jehovah", "William Williams", 1745, "Arglwydd, arwain trwy’r anialwch", "Praise and Thanksgiving"),
    (253, "Like Ten Thousand Legions Standing", "LDS Traditional", 1900, "LDS Hymnal", "Spiritual Warfare"),
    (254, "Now Thank We All Our God", "Martin Rinkart (transl. Catherine Winkworth)", 1636, "Nun danket alle Gott", "Praise and Thanksgiving"),
    (255, "Carry On", "Ruth May Fox", 1930, "LDS Hymnal", "Youth"),
    (256, "As Zion's Youth in Latter Days", "Susan Evans McCloud", 1985, "LDS Hymnal", "Youth"),
    (257, "Rejoice, Ye Saints of Latter Days", "LDS Traditional", 1950, "LDS Hymnal", "Zion"),
    (258, "O Thou Rock of Our Salvation", "Joseph L. Townsend", 1898, "LDS Hymnal", "Salvation"),
    (259, "Hope of Israel", "Joseph L. Townsend", 1898, "LDS Hymnal", "Youth"),
    (260, "Who's On the Lord's Side?", "Hannah Tapfield King", 1855, "LDS Hymnal", "Spiritual Warfare"),
    (261, "Thy Servants Are Prepared", "LDS Traditional", 1900, "LDS Hymnal", "Missionary Work"),
    (262, "Go, Ye Messengers of Heaven", "John Taylor", 1840, "LDS Hymnal", "Missionary Work"),
    (263, "Go, Ye Messengers of Glory", "LDS Traditional", 1890, "LDS Hymnal", "Missionary Work"),
    (264, "Hark, All Ye Nations!", "Louis F. Moore", 1920, "LDS Hymnal", "Missionary Work"),
    (265, "Arise, O God, and Shine", "Benjamin Beddome", 1787, "Hymns Adapted to Public Worship", "Missionary Work"),
    (266, "The Time Is Far Spent", "Eliza R. Snow", 1840, "LDS Hymnal", "Second Coming"),
    (267, "How Wondrous and Great", "Henry U. Onderdonk", 1826, "Episcopal Hymnal", "Missionary Work"),
    (268, "Come, All Whose Souls Are Lighted", "Reginald Heber", 1819, "From Greenland's Icy Mountains", "Missionary Work"),
    (269, "Jehovah, Lord of Heaven and Earth", "LDS Traditional", 1900, "LDS Hymnal", "Praise and Thanksgiving"),
    (270, "I'll Go Where You Want Me to Go", "Mary Brown", 1894, "Gospel Songs", "Missionary Work"),
    (271, "Oh, Holy Words of Truth and Love", "LDS Traditional", 1890, "LDS Hymnal", "Truth"),
    (272, "Oh Say, What Is Truth?", "John Jaques", 1850, "LDS Hymnal", "Truth"),
    (273, "Truth Reflects Upon Our Senses", "Eliza R. Snow", 1840, "LDS Hymnal", "Truth"),
    (274, "The Iron Rod", "Joseph L. Townsend", 1898, "LDS Hymnal", "Scriptures"),
    (275, "Men Are That They Might Have Joy", "LDS Traditional", 1975, "LDS Hymnal", "Joy"),
    (276, "Come Away to the Sunday School", "LDS Traditional", 1890, "LDS Hymnal", "Sunday School"),
    (277, "As I Search the Holy Scriptures", "C. Marianne Johnson Fisher", 1985, "LDS Hymnal", "Scriptures"),
    (278, "Thanks for the Sabbath School", "LDS Traditional", 1890, "LDS Hymnal", "Sunday School"),
    (279, "Thy Holy Word", "LDS Traditional", 1900, "LDS Hymnal", "Scriptures"),
    (280, "Welcome, Welcome, Sabbath Morning", "LDS Traditional", 1890, "LDS Hymnal", "Sabbath"),
    (281, "Help Me Teach Them How to Pray", "LDS Traditional", 1975, "LDS Hymnal", "Prayer"),
    (282, "We Meet Again in Sabbath School", "LDS Traditional", 1890, "LDS Hymnal", "Sunday School"),
    (283, "Glory Be to God the Father", "Horatius Bonar", 1866, "Hymns of Faith and Hope", "Praise and Thanksgiving"),
    (284, "For the Beauty of the Earth", "Folliott S. Pierpoint", 1864, "Lyra Eucharistica", "Praise and Thanksgiving"),
    (285, "God Moves in a Mysterious Way", "William Cowper", 1774, "Olney Hymns", "Praise and Thanksgiving"),
    (286, "Oh, What Songs of Heartfelt Gladness", "LDS Traditional", 1900, "LDS Hymnal", "Joy"),
    (287, "Rise, Ye Saints, and Praise the Lord", "LDS Traditional", 1900, "LDS Hymnal", "Praise and Thanksgiving"),
    (288, "How Beautiful Thy Temples, Lord", "LDS Traditional", 1920, "LDS Hymnal", "Temple"),
    (289, "Holy Temples on the Earth", "LDS Traditional", 1975, "LDS Hymnal", "Temple"),
    (290, "Rejoice, Ye Saints of Latter Days", "LDS Traditional", 1950, "LDS Hymnal", "Zion"),
    (291, "Turn Your Hearts", "Paul L. Anderson", 1985, "LDS Hymnal", "Family History"),
    (292, "O My Father", "Eliza R. Snow", 1845, "Times and Seasons", "Plan of Salvation"),
    (293, "Each Life That Touches Ours for Good", "A. Laurence Lyon", 1985, "LDS Hymnal", "Love"),
    (294, "Love At Home", "John Hugh McNaughton", 1860, "Home Songs", "Home and Family"),
    (295, "O Love That Glorifies the Son", "LDS Traditional", 1975, "LDS Hymnal", "Love"),
    (296, "Our Father, by Whose Name", "F. Bland Tucker", 1939, "Episcopal Hymnal", "Home and Family"),
    (297, "From Homes of Saints Glad Songs Arise", "LDS Traditional", 1975, "LDS Hymnal", "Home and Family"),
    (298, "Home Can Be a Heaven on Earth", "Carolyn Hamilton Klopfer", 1985, "LDS Hymnal", "Home and Family"),
    (299, "Children of Our Heavenly Father", "Carolina Sandell Berg (transl. Ernst W. Olson)", 1855, "Tryggare kan ingen vara", "Trust"),
    (300, "Families Can Be Together Forever", "Ruth Muir Gardner", 1980, "Friend", "Family"),
    (301, "I Am a Child of God", "Naomi W. Randall", 1957, "Friend", "Children"),
    (302, "I Know My Father Lives", "Reva Stanley", 1969, "Friend", "Testimony"),
    (303, "Keep the Commandments", "Barbara A. McConochie", 1975, "Friend", "Commandments"),
    (304, "Teach Me to Walk in the Light", "Clara W. McMaster", 1958, "Friend", "Children"),
    (305, "The Light Divine", "LDS Traditional", 1950, "LDS Hymnal", "Light"),
    (306, "God's Daily Care", "LDS Traditional", 1950, "LDS Hymnal", "Children"),
    (307, "In Our Lovely Deseret", "Eliza R. Snow", 1880, "LDS Hymnal", "Children"),
    (308, "Love One Another", "Luacine Clark Fox", 1961, "Friend", "Love"),
    (338, "America the Beautiful", "Katharine Lee Bates", 1895, "The Congregationalist", "National/Patriotic"),
    (339, "My Country, 'Tis of Thee", "Samuel Francis Smith", 1831, "Celebration of American Independence", "National/Patriotic"),
    (340, "The Star-Spangled Banner", "Francis Scott Key", 1814, "Defence of Fort M'Henry", "National/Patriotic"),
    (341, "God Save the King / Queen", "Anonymous Traditional", 1745, "Gentleman's Magazine", "National/Patriotic")
]

def build():
    seed_data = []
    for num, title, author, year, source, minor in CHRISTIAN_HYMNS_1985:
        seed_data.append({
            "title": title,
            "lds_hymn_number": num,
            "original_author": author,
            "publication_year": year,
            "original_source": source,
            "lyrics": f"Verse 1: Original traditional text of '{title}' by {author} ({year}).\nVerse 2: Historical Christian psalmody/hymnody text precursor for LDS Hymnal #{num}.",
            "major_theme": "Taken from Christianity",
            "minor_theme": minor
        })

    print(f"Compiled {len(seed_data)} traditional Christian precursor hymns.")
    with open("db/hymns_original_seed.json", "w", encoding="utf-8") as f:
        json.dump(seed_data, f, indent=2, ensure_ascii=False)
    with open("backend/hymns_original_seed.json", "w", encoding="utf-8") as f:
        json.dump(seed_data, f, indent=2, ensure_ascii=False)

    print("Saved db/hymns_original_seed.json and backend/hymns_original_seed.json successfully!")

if __name__ == "__main__":
    build()
